language: c
sudo: false
addons:
  apt:
    sources:
    - avsm
    packages:
    - aspcud
    - ocaml
    - ocaml-native-compilers
    - camlp4-extra
    - opam
script:
- opam init -a "git://github.com/ocaml/opam-repository" --comp="$OCAML_VERSION"
- eval `opam config env`
- opam install stog
- stog --package stog.markdown index.html
- cd stog-output
- git init
- git config user.name "Travis Worker"
- git config user.email "travis@travis-ci.org"
- git remote add upstream https://$GH_TOKEN@github.com/$USERNAME/$REPO.git > /dev/null
  2>&1
- git fetch upstream
- git reset upstream/gh-pages
- git add -A .
- git commit -m "Update $(date '+%m/%d/%y %H:%M')."
- git push -q upstream HEAD:gh-pages
notifications:
  email: false
env:
  global:
  - OCAML_VERSION=4.03.0
  - OPAMYES=1
  - USERNAME=atrieu
  - REPO=blogtest
  - secure: L36CudyUUH+OaToi7DbloDWSby8sZ7QWXdFIxJVnlCzrBAn+AaLqb36EOxMRA5LbiocKuNzbNBa+yOM4dQ8KCQtQBSoKDUgBZg8eHDoWCvU+fPJcCBjraQEnpQ9L612MgTk6UsW/T3U8tt3cWnz0jGeTkE5LWeHMKeZE1rx2vaEu0p0ohmpt/PzoK+FvhmejoUo4qLNbHn8j73NZbHvsQmgOQEdGwkDN+bgR1Y8pm23VEpp1Ex4AicDEMYjW/hKaVpG0dZBjvVyk2Uz2AM0u7abx42awu0APDg6Yth97zNNM6JFqj86xi5UDxeA7iylvweG0LQ2Fv9rkozpeMkqwa8N7XOx7U65T1/NA6UyiZtGZMsxsm7Yqnil2xTsVIQnmyq0PrQjuWlx21Pl8dYYzQFUQsJybc8un8EknxXvO1sWCRXpl4bP4kvw61IBeUONCw5ZbYWm9nXxca24kaVQw3GJDX2g8d1PkVECm0wO0mtgguyCkDnHEVYyN/3IwIE106+UuVRu8wbaQT608V0hME8yhaEvX00PonRGHiOsOsQ8KiGyD+Q/V95JWxRbGaCPGcO8AR9BSn7I+FarO6qnqpz1WRXW6JwHj9ffKUhHpnNW5N4CvLttsgETtQM1IInZh9boQkagSAe7QrXgl9BuqZxU4cwZWn9DBOKjSd1pmpHM=
