language: c
sudo: false
addons:
  apt:
    sources:
    - avsm
    packages:
    - ocaml
    - ocaml-native-compilers
    - camlp4-extra
    - opam
script:
  - opam init -a "git://github.com/ocaml/opam-repository" --comp="$OCAML_VERSION"
  - eval `opam config env`
  - opam install stog
  - stog --package stog.markdown index.html
  - cd stog-output
  - git init
  - git config user.name "Travis Worker"
  - git config user.email "travis@travis-ci.org"
  - git remote add upstream https://$GH_TOKEN@github.com/$USERNAME/$REPO.git > /dev/null 2>&1
  - git fetch upstream
  - git reset upstream/gh-pages
  - git add -A .
  - git commit -m "Update $(date '+%m/%d/%y %H:%M')."
  - git push -q upstream HEAD:gh-pages
notifications:
  email: false
env:
  global:
    - secure: HAEvx3nOMmdILc2l1le6hCKqadOR9BcILlrH+Rnv2c98F7xBIBYEo8jcTFKhVM7LX0bGK8WX+oyH9aeL3LR1SZgNfHrF0qPPZGStVETgcrubGRXqr5fDFjkE49J90s6USr0QG5IctVCJYmOot4Llk95t7p9q1WOfnbnSjTJPsKlrPvho1XRQwTVI/Rw7iA4B8LuwljhqoSfPzXgxuARG+KQVB6zIxUdOlOEm4MvXZ9MCne0jCxcBvMvhfyafaMK7RwrQpV9Jga/9WbOSrqMfIaCqFwFqaag2rtSWZljS47RrHjl5WZRwQDsGiWFi7p3njr2XlVqjw2ha/398CHrjvi3OUG2BjDYV7FoXtOXkIxfYTWp2VPnN+gKjAPSw611NobNmdhRAx0k40lH8KIyEjxMqS2S1mb0bFQWc8iP+wDQKtO/G0WvknIYtuQT7rF4X5sBFXJVzOWOG55u92oQlOMKvCwk3S+yeGTjb9B0QL9EsBgsX/XJEifQQBX1mIpK1k45oXSJVUkgxhfYVqXqVW9QKjBWcC+nfcK1z4hzEoTdzslFzlCyo4ZaQqUQ/attLQlH5mRL9Br2l3ttJpRg8PnE/pOI/A2J8LIlmXwfa9sNOZa5uQrOddIjUyTNi6jI6I/06JUcuN1zTZ7JP5jBPYCUKXODNz/be0br0pVflxzE=
    - OCAML_VERSION=4.03.0
    - OPAMYES=1
    - USERNAME=atrieu
    - REPO=blogtest
