language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
script: bash -ex .travis-ocaml.sh
after_success:
  - eval $(opam config env)
  - opam install stog
  - stog --package stog.markdown index.html
  - git clone -b gh-pages "https://$GH_TOKEN@github.com/$USERNAME/$REPO.git" gh-pages
  - cd gh-pages
  - git config user.name "Travis Worker"
  - git config user.email "travis@travis-ci.org"
  - cp ../stog-output/*.{html,css} ./
  - git add -A .
  - git commit -m "Update $(date '+%m/%d/%y %H:%M')."
  - git push -q origin gh-pages
notifications:
  email: false
env:
  global:
    - secure: HAEvx3nOMmdILc2l1le6hCKqadOR9BcILlrH+Rnv2c98F7xBIBYEo8jcTFKhVM7LX0bGK8WX+oyH9aeL3LR1SZgNfHrF0qPPZGStVETgcrubGRXqr5fDFjkE49J90s6USr0QG5IctVCJYmOot4Llk95t7p9q1WOfnbnSjTJPsKlrPvho1XRQwTVI/Rw7iA4B8LuwljhqoSfPzXgxuARG+KQVB6zIxUdOlOEm4MvXZ9MCne0jCxcBvMvhfyafaMK7RwrQpV9Jga/9WbOSrqMfIaCqFwFqaag2rtSWZljS47RrHjl5WZRwQDsGiWFi7p3njr2XlVqjw2ha/398CHrjvi3OUG2BjDYV7FoXtOXkIxfYTWp2VPnN+gKjAPSw611NobNmdhRAx0k40lH8KIyEjxMqS2S1mb0bFQWc8iP+wDQKtO/G0WvknIYtuQT7rF4X5sBFXJVzOWOG55u92oQlOMKvCwk3S+yeGTjb9B0QL9EsBgsX/XJEifQQBX1mIpK1k45oXSJVUkgxhfYVqXqVW9QKjBWcC+nfcK1z4hzEoTdzslFzlCyo4ZaQqUQ/attLQlH5mRL9Br2l3ttJpRg8PnE/pOI/A2J8LIlmXwfa9sNOZa5uQrOddIjUyTNi6jI6I/06JUcuN1zTZ7JP5jBPYCUKXODNz/be0br0pVflxzE=
    - OCAML_VERSION=4.03
    - OPAMYES=1
    - UBUNTU_TRUSTY=1
    - USERNAME=atrieu
    - REPO=blogtest
dist: trusty
