language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
notifications
  email: false
env:
  - OCAML_VERSION=4.02
  - PINS="ocf:https://github.com/zoggy/ocf.git#0.4.1"
os:
  - linux
